baseURL = 'https://improneuf.github.io/improneuf.no/'
title = 'Impro Neuf'
theme = 'improneuf'
defaultContentLanguage = 'no'
defaultContentLanguageInSubdir = false

[languages]
  [languages.no]
    languageCode = 'nb-NO'
    languageName = 'Norsk'
    weight = 1
    contentDir = 'content/no'

    [[languages.no.menu.main]]
        name = "Hjem"
        url = "/"
        weight = 10

    [[languages.no.menu.main]]
        name = "Forestillinger"
        url = "/#shows"
        weight = 20

    [[languages.no.menu.main]]
        name = "Workshops"
        url = "/#workshops"
        weight = 30

    [[languages.no.menu.main]]
        name = "Om oss"
        url = "/about/"
        identifier = "about"
        weight = 40

    [[languages.no.menu.main]]
        name = "Historie"
        parent = "about"
        url = "/about/historie/"
        weight = 10

    [[languages.no.menu.main]]
        name = "Offentlige regnskaper"
        parent = "about"
        url = "/about/offentlige-regnskaper/"
        weight = 20

    [[languages.no.menu.main]]
        name = "Roller"
        parent = "about"
        url = "/about/roller/"
        weight = 30

    [[languages.no.menu.main]]
        name = "Lærere / frivillige"
        parent = "about"
        url = "/about/laerere-frivillige/"
        weight = 40

    [[languages.no.menu.main]]
        name = "Team"
        parent = "about"
        url = "/about/team/"
        weight = 50

    [[languages.no.menu.main]]
        name = "Hvor"
        parent = "about"
        url = "/about/hvor/"
        weight = 60

    [[languages.no.menu.main]]
        name = "Hvem"
        parent = "about"
        url = "/about/hvem/"
        weight = 70

    [[languages.no.menu.main]]
        name = "Kontakt oss"
        url = "/contact/"
        identifier = "contact"
        weight = 50

    [[languages.no.menu.main]]
        name = "Anonym tilbakemelding"
        parent = "contact"
        url = "/contact/anonym-tilbakemelding/"
        weight = 10

    [[languages.no.menu.main]]
        name = "Rapport/varsel"
        parent = "contact"
        url = "/contact/rapport-varsel/"
        weight = 20

    [[languages.no.menu.main]]
        name = "Kontakt styret"
        parent = "contact"
        url = "/contact/kontakt-styret/"
        weight = 30

    [[languages.no.menu.main]]
        name = "Hvem spør jeg om ting?"
        parent = "contact"
        url = "/contact/hvem-spor-jeg/"
        weight = 40

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 2
    contentDir = 'content/en'

    [[languages.en.menu.main]]
        name = "Home"
        url = "/en/"
        weight = 10

    [[languages.en.menu.main]]
        name = "Shows"
        url = "/en/#shows"
        weight = 20

    [[languages.en.menu.main]]
        name = "Workshops"
        url = "/en/#workshops"
        weight = 30

    [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        identifier = "about"
        weight = 40

    [[languages.en.menu.main]]
        name = "History"
        parent = "about"
        url = "/en/about/history/"
        weight = 10

    [[languages.en.menu.main]]
        name = "Public records"
        parent = "about"
        url = "/en/about/public-records/"
        weight = 20

    [[languages.en.menu.main]]
        name = "Roles"
        parent = "about"
        url = "/en/about/roles/"
        weight = 30

    [[languages.en.menu.main]]
        name = "Teachers / volunteers"
        parent = "about"
        url = "/en/about/teachers-volunteers/"
        weight = 40

    [[languages.en.menu.main]]
        name = "Teams"
        parent = "about"
        url = "/en/about/teams/"
        weight = 50

    [[languages.en.menu.main]]
        name = "Where"
        parent = "about"
        url = "/en/about/where/"
        weight = 60

    [[languages.en.menu.main]]
        name = "Who"
        parent = "about"
        url = "/en/about/who/"
        weight = 70

    [[languages.en.menu.main]]
        name = "Contact Us"
        url = "/en/contact/"
        identifier = "contact"
        weight = 50

    [[languages.en.menu.main]]
        name = "Anonymous feedback"
        parent = "contact"
        url = "/en/contact/anonymous-feedback/"
        weight = 10

    [[languages.en.menu.main]]
        name = "Report/notification"
        parent = "contact"
        url = "/en/contact/report-notification/"
        weight = 20

    [[languages.en.menu.main]]
        name = "Contact the board"
        parent = "contact"
        url = "/en/contact/contact-board/"
        weight = 30

    [[languages.en.menu.main]]
        name = "Who do I ask about stuff?"
        parent = "contact"
        url = "/en/contact/who-to-ask/"
        weight = 40
